import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

/** @type {import("eslint").Linter.Config[]} */
const eslintConfig = [
  ...nextCoreWebVitals,
  {
    // coverage/ is generated by vitest; .next/ and next-env.d.ts are already
    // ignored by eslint-config-next/core-web-vitals.
    ignores: ["coverage/**"],
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              // The shared API contract package is the only workspace member
              // Web may import; Obsidian and every other app stay unreachable.
              group: [
                "@workspace/*",
                "!@workspace/api-client",
                "**/obsidian-plugin/**",
              ],
            },
          ],
        },
      ],
    },
  },
];

export default eslintConfig;
