"""Framework-neutral exclusion-policy domain package.

Closed rule contracts and immutable revision/subject values, shared locator
and operand normalization with the bounded glob compiler, the pure deny-only
evaluator, the closed RFC 8785-compatible canonical JSON encoder, the typed
signed snapshot/keyset payload builders with their signing ports, the typed
error bound to the closed ``exclusion_policy_*`` registry codes, and the
low-cardinality evaluation metrics contracts. The package imports no web
framework, database driver, provider SDK, cryptography library or composition
root; it reuses the canonical ``SourceType`` and ``CanonicalMediaType`` value
semantics.
"""

from personal_os.exclusion_policy.canonical_json import (
    MAXIMUM_SAFE_INTEGER,
    CanonicalJsonValue,
    canonicalize_json_value,
)
from personal_os.exclusion_policy.contracts import (
    EVALUATOR_CONTRACT,
    EXTENSION_MAXIMUM_CHARACTERS,
    EXTENSION_MINIMUM_CHARACTERS,
    GLOB_MAXIMUM_BYTES,
    GLOB_MAXIMUM_SEGMENTS,
    GLOB_MAXIMUM_WILDCARD_TOKENS,
    LOCATOR_MAXIMUM_BYTES,
    LOCATOR_MAXIMUM_SEGMENTS,
    LOCATOR_SEGMENT_MAXIMUM_BYTES,
    MAXIMUM_RULES_PER_REVISION,
    MAXIMUM_SIZE_BYTES_CEILING,
    CompiledGlob,
    EnforcedPolicyDecision,
    ExactSourceIdOperand,
    ExclusionPolicyRevision,
    ExclusionRule,
    ExtensionOperand,
    FolderPrefixOperand,
    GlobLiteralPart,
    GlobSegment,
    GlobSegmentPart,
    GlobStarPart,
    MaximumSizeOperand,
    MediaTypeOperand,
    PathGlobOperand,
    PolicySubject,
    PolicySubjectField,
    PreviewMatchState,
    RawPolicyDecision,
    RuleKind,
    RuleOperand,
    SourceTypeOperand,
    preview_match_state,
)
from personal_os.exclusion_policy.enforcement import (
    ActivePolicySnapshotMaterial,
    AllowedPolicyRevisionBinding,
    PolicyDecision,
    PolicyEnforcementService,
    PublicationPolicyEvidence,
    enforce_policy_decision,
    evaluate_policy_decision,
    parse_verified_policy_revision,
)
from personal_os.exclusion_policy.errors import (
    INPUT_REASONS,
    PAYLOAD_CONTRACT_REASONS,
    POLICY_DENIAL_ERROR_CODES,
    POLICY_SYSTEM_ERROR_CODES,
    ExclusionPolicyError,
    PolicyContractError,
    is_policy_system_failure,
    payload_contract_error,
)
from personal_os.exclusion_policy.evaluation import (
    PolicyEvaluationOutcome,
    evaluate_policy,
)
from personal_os.exclusion_policy.metrics import (
    EXCLUSION_POLICY_METRIC_CONTRACTS,
    EvaluationMetricOutcome,
    EvaluationRecord,
    ExclusionPolicyMetrics,
    InMemoryExclusionPolicyMetrics,
    PolicyBoundary,
)
from personal_os.exclusion_policy.normalization import (
    RULE_FINGERPRINT_CONTRACT,
    compile_glob,
    fold_ascii_lowercase,
    glob_matches,
    normalize_locator,
    normalize_rule,
)
from personal_os.exclusion_policy.signatures import (
    ED25519_PUBLIC_KEY_BYTES,
    ED25519_SEED_BYTES,
    ED25519_SIGNATURE_BYTES,
    KEY_ID_PREFIX,
    KEYSET_MAXIMUM_NON_RETIRED_KEYS,
    KEYSET_PAYLOAD_CONTRACT,
    KEYSET_SIGNING_DOMAIN,
    SIGNATURE_ALGORITHM,
    SIGNED_SNAPSHOT_MAXIMUM_BYTES,
    SNAPSHOT_PAYLOAD_CONTRACT,
    SNAPSHOT_SIGNING_DOMAIN,
    PolicyKeysetKey,
    PolicyKeysetState,
    PolicySignatureVerifier,
    PolicySigner,
    build_keyset_payload,
    build_signed_message,
    build_snapshot_payload,
    compute_payload_sha256_hex,
    compute_signed_snapshot_envelope_size,
    decode_base64url_without_padding,
    derive_ed25519_key_id,
    encode_base64url_without_padding,
    is_wellformed_ed25519_key_id,
)

__all__ = [
    "ED25519_PUBLIC_KEY_BYTES",
    "ED25519_SEED_BYTES",
    "ED25519_SIGNATURE_BYTES",
    "EVALUATOR_CONTRACT",
    "EXCLUSION_POLICY_METRIC_CONTRACTS",
    "EXTENSION_MAXIMUM_CHARACTERS",
    "EXTENSION_MINIMUM_CHARACTERS",
    "GLOB_MAXIMUM_BYTES",
    "GLOB_MAXIMUM_SEGMENTS",
    "GLOB_MAXIMUM_WILDCARD_TOKENS",
    "INPUT_REASONS",
    "KEYSET_MAXIMUM_NON_RETIRED_KEYS",
    "KEYSET_PAYLOAD_CONTRACT",
    "KEYSET_SIGNING_DOMAIN",
    "KEY_ID_PREFIX",
    "LOCATOR_MAXIMUM_BYTES",
    "LOCATOR_MAXIMUM_SEGMENTS",
    "LOCATOR_SEGMENT_MAXIMUM_BYTES",
    "MAXIMUM_RULES_PER_REVISION",
    "MAXIMUM_SAFE_INTEGER",
    "MAXIMUM_SIZE_BYTES_CEILING",
    "PAYLOAD_CONTRACT_REASONS",
    "POLICY_DENIAL_ERROR_CODES",
    "POLICY_SYSTEM_ERROR_CODES",
    "RULE_FINGERPRINT_CONTRACT",
    "SIGNATURE_ALGORITHM",
    "SIGNED_SNAPSHOT_MAXIMUM_BYTES",
    "SNAPSHOT_PAYLOAD_CONTRACT",
    "SNAPSHOT_SIGNING_DOMAIN",
    "ActivePolicySnapshotMaterial",
    "AllowedPolicyRevisionBinding",
    "CanonicalJsonValue",
    "CompiledGlob",
    "EnforcedPolicyDecision",
    "EvaluationMetricOutcome",
    "EvaluationRecord",
    "ExactSourceIdOperand",
    "ExclusionPolicyError",
    "ExclusionPolicyMetrics",
    "ExclusionPolicyRevision",
    "ExclusionRule",
    "ExtensionOperand",
    "FolderPrefixOperand",
    "GlobLiteralPart",
    "GlobSegment",
    "GlobSegmentPart",
    "GlobStarPart",
    "InMemoryExclusionPolicyMetrics",
    "MaximumSizeOperand",
    "MediaTypeOperand",
    "PathGlobOperand",
    "PolicyBoundary",
    "PolicyContractError",
    "PolicyDecision",
    "PolicyEnforcementService",
    "PolicyEvaluationOutcome",
    "PolicyKeysetKey",
    "PolicyKeysetState",
    "PolicySignatureVerifier",
    "PolicySigner",
    "PolicySubject",
    "PolicySubjectField",
    "PreviewMatchState",
    "PublicationPolicyEvidence",
    "RawPolicyDecision",
    "RuleKind",
    "RuleOperand",
    "SourceTypeOperand",
    "build_keyset_payload",
    "build_signed_message",
    "build_snapshot_payload",
    "canonicalize_json_value",
    "compile_glob",
    "compute_payload_sha256_hex",
    "compute_signed_snapshot_envelope_size",
    "decode_base64url_without_padding",
    "derive_ed25519_key_id",
    "encode_base64url_without_padding",
    "enforce_policy_decision",
    "evaluate_policy",
    "evaluate_policy_decision",
    "fold_ascii_lowercase",
    "glob_matches",
    "is_policy_system_failure",
    "is_wellformed_ed25519_key_id",
    "normalize_locator",
    "normalize_rule",
    "parse_verified_policy_revision",
    "payload_contract_error",
    "preview_match_state",
]
