"""Password policy, the offline common-password blocklist and the Argon2id pins.

The policy is exactly spec 8.1: 15-128 Unicode code points, spaces allowed, no
composition rule, no periodic expiry, and rejection of values whose
lowercased SHA-256 digest is present in the committed offline blocklist
artifact. The artifact is generated by
``tools/generate_password_blocklist.py`` from the SecLists top-10000 source
and ships only sorted lowercase hex digests plus provenance; no raw password
list is packaged, logged or held in memory at runtime.

The probe hashes the lowercased candidate, locates the digest in the sorted
artifact with a bounded binary search and confirms membership with
:func:`hmac.compare_digest`, so no password text is ever compared directly.
The pinned Argon2id work parameters (Global Constraints) live here as the
single source of truth the composition-root adapter consumes.
"""

from __future__ import annotations

import bisect
import hashlib
import hmac
import importlib.resources
from dataclasses import dataclass
from typing import Final

from personal_os.authentication.errors import AuthenticationError
from personal_os.error_contracts.codes import ErrorCode

#: Password length bounds in Unicode code points (spec 8.1).
PASSWORD_MINIMUM_LENGTH_CHARACTERS: Final[int] = 15
PASSWORD_MAXIMUM_LENGTH_CHARACTERS: Final[int] = 128

#: Argon2id work parameters (Global Constraints): memory cost in KiB.
ARGON2ID_MEMORY_COST_KIB: Final[int] = 65_536
#: Argon2id work parameters (Global Constraints): time cost in iterations.
ARGON2ID_TIME_COST_ITERATIONS: Final[int] = 3
#: Argon2id work parameters (Global Constraints): lane count.
ARGON2ID_PARALLELISM_LANES: Final[int] = 1
#: Argon2id work parameters (Global Constraints): salt length in bytes.
ARGON2ID_SALT_LENGTH_BYTES: Final[int] = 16
#: Argon2id work parameters (Global Constraints): hash length in bytes.
ARGON2ID_HASH_LENGTH_BYTES: Final[int] = 32

#: Committed artifact: package resource path of the sorted digest lines.
COMMON_PASSWORD_BLOCKLIST_RESOURCE_NAME: Final[str] = "common-password-sha256-v1.txt"

#: Committed artifact: the digests of the 10,000 source lines. Digests are
#: computed over lowercased lines, so the 87 case-variant lines of the source
#: (``password``/``Password``/``PASSWORD`` and peers) collapse onto one digest
#: each, leaving 9,913 unique sorted digests.
COMMON_PASSWORD_BLOCKLIST_DIGEST_COUNT: Final[int] = 9_913

#: One artifact line is exactly a 64-character lowercase hex SHA-256 digest.
_BLOCKLIST_DIGEST_LENGTH: Final[int] = 64


@dataclass(frozen=True, slots=True)
class PasswordBlocklist:
    """Immutable sorted set of lowercase SHA-256 digests of common passwords.

    ``digests`` is bytewise-ascending and duplicate-free by construction, so
    the probe is a bounded binary search plus one constant-time confirmation.
    """

    digests: tuple[str, ...]

    @classmethod
    def from_digest_text(cls, digest_text: str) -> PasswordBlocklist:
        """Parse and validate the committed artifact bytes.

        Rejects any line that is not one 64-character lowercase hex digest,
        any empty artifact and any unsorted or duplicate ordering, so a
        replaced or corrupted artifact fails closed at load time. The error
        message never includes artifact content.
        """
        lines = digest_text.splitlines()
        if not lines:
            raise ValueError("blocklist digest lines are empty")
        for line in lines:
            if len(line) != _BLOCKLIST_DIGEST_LENGTH or line != line.lower():
                raise ValueError("blocklist digest lines are malformed")
            try:
                int(line, 16)
            except ValueError as cause:
                raise ValueError("blocklist digest lines are malformed") from cause
        if list(lines) != sorted(lines) or len(set(lines)) != len(lines):
            raise ValueError("blocklist digest lines are malformed")
        return cls(digests=tuple(lines))

    def is_blocked(self, password: str) -> bool:
        """Return whether the lowercased candidate is a listed common value.

        Only the digest ever crosses this boundary: the probe binary-searches
        the sorted artifact for the candidate digest and confirms the hit with
        a constant-time comparison.
        """
        candidate_digest = hashlib.sha256(password.lower().encode("utf-8")).hexdigest()
        index = bisect.bisect_left(self.digests, candidate_digest)
        if index >= len(self.digests):
            return False
        return hmac.compare_digest(self.digests[index], candidate_digest)

    def __repr__(self) -> str:
        return f"PasswordBlocklist(digest_count={len(self.digests)})"


def load_common_password_blocklist() -> PasswordBlocklist:
    """Load the committed blocklist artifact through package resources.

    Reads only the digest file (never any raw list) from
    ``personal_os.authentication`` data resources, validates its shape and
    pins the expected digest count, then returns the frozen immutable view.
    """
    resource = importlib.resources.files("personal_os.authentication").joinpath(
        "data",
        COMMON_PASSWORD_BLOCKLIST_RESOURCE_NAME,
    )
    blocklist = PasswordBlocklist.from_digest_text(resource.read_text(encoding="utf-8"))
    if len(blocklist.digests) != COMMON_PASSWORD_BLOCKLIST_DIGEST_COUNT:
        raise ValueError("blocklist digest count does not match the pinned artifact")
    return blocklist


def validate_new_password(password: str, blocklist: PasswordBlocklist) -> str:
    """Validate one new password against the policy and offline blocklist.

    Returns the accepted value unchanged. Any failure — length outside
    15-128 code points or a blocklisted common value — raises
    :class:`AuthenticationError` with the generic ``authentication_failed``
    code and no safe detail, mirroring the login contract so enrollment and
    change surfaces never distinguish the rejection reason publicly.
    """
    if (
        len(password) < PASSWORD_MINIMUM_LENGTH_CHARACTERS
        or len(password) > PASSWORD_MAXIMUM_LENGTH_CHARACTERS
    ):
        raise AuthenticationError(ErrorCode.AUTHENTICATION_FAILED)
    if blocklist.is_blocked(password):
        raise AuthenticationError(ErrorCode.AUTHENTICATION_FAILED)
    return password
