import tseslint from "typescript-eslint";

/** @type {import("eslint").Linter.Config[]} */
const eslintConfig = [
  {
    // src/generated/ holds the openapi-typescript output (regenerated, never
    // hand edited); coverage/ is generated by vitest.
    ignores: ["src/generated/**", "coverage/**"],
  },
  ...tseslint.configs.strict,
  {
    files: ["**/*.ts"],
    rules: {
      // The shared client must never depend on its consumers.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "@workspace/web-runtime",
                "@workspace/obsidian-plugin",
                "**/apps/web/**",
                "**/obsidian-plugin/**",
              ],
            },
          ],
        },
      ],
    },
  },
];

export default eslintConfig;
