import tseslint from "typescript-eslint";

/** @type {import("eslint").Linter.Config[]} */
const eslintConfig = [
  {
    // dist/ is generated by the esbuild bundler; coverage/ is generated by vitest.
    ignores: ["dist/**", "coverage/**"],
  },
  ...tseslint.configs.strict,
  {
    files: ["**/*.ts"],
    rules: {
      // Sole narrow exception: the intentional empty override lifecycle methods.
      "@typescript-eslint/no-empty-function": [
        "error",
        { allow: ["overrideMethods"] },
      ],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              // The shared API contract package is the only workspace member
              // the plugin may import; Web and every other app stay
              // unreachable.
              group: [
                "@workspace/*",
                "!@workspace/api-client",
                "**/apps/web/**",
              ],
            },
          ],
        },
      ],
    },
  },
];

export default eslintConfig;
