import tseslint from "typescript-eslint";

/** @type {import("eslint").Linter.Config[]} */
const eslintConfig = [
  {
    // dist/ is generated by the esbuild bundler; coverage/ is generated by vitest.
    ignores: ["dist/**", "coverage/**"],
  },
  ...tseslint.configs.strict,
  {
    files: ["**/*.ts"],
    rules: {
      // Sole narrow exception: the intentional empty override lifecycle methods.
      "@typescript-eslint/no-empty-function": [
        "error",
        { allow: ["overrideMethods"] },
      ],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@workspace/web-runtime", "**/apps/web/**"],
            },
          ],
        },
      ],
    },
  },
];

export default eslintConfig;
